### ISSUE TITLE
How to use @alias and ::namespace ?

### ISSUE THREAD

**Issue by ethyde** [bitmade/node-twig#3]
Hi,

I don't find any things about how to define/use @alias and or namespace.

I found `AliasLoader.php`, but how to use it ?

Thx.

**Comment by mamoschli** [comment]
Hi,
you're right, we are missing some documentation here.

Since we are using this package in our dev-tools you can have a look there:
https://github.com/bitmade/dev-tools/blob/master/src/twigEngine.js

So aliases basically are just key value pairs passed into the options under the aliases key.
The values are paths to the folders you want to alias.

Let me here if that works for you.

**Comment by ethyde** [comment]
Hi,

Yes, thanks !
